default: &default
  adapter: postgresql
  encoding: unicode
  host: localhost
  username: postgres
  password: 123456789
  pool: 5

development:
  <<: *default
  database: site_development


test:
  <<: *default
  database: agenda_development

production:
  <<: *default
  database: agenda_development
