default: &default
  adapter: postgresql
  encoding: unicode
  host: 10.233.38.16
  username: postgres
  password: codhab072771472
  pool: 5

development:
  <<: *default
  database: site_development


test:
  <<: *default
  database: site_development

production:
  <<: *default
  database: site_development
